### ISSUE TITLE
RpcOpenPrinter fail!

### ISSUE THREAD

**Issue by kokxxoo** [BeichenDream/BadPotato#1]
[*] PipeName : \\.\pipe\5bf6d39388ab4720844b4415388786f0\pipe\spoolss
[*] ConnectPipeName : \\SHYifun/pipe/5bf6d39388ab4720844b4415388786f0
[*] CreateNamedPipeW Success! IntPtr:844
[!] RpcOpenPrinter fail!

**Comment by BeichenDream** [comment]
请检查 Windows 版本是否在2012及以上

**Comment by mooneee** [comment]
[*] ImpersonateNamedPipeClient Success!
[*] OpenThreadToken Success! IntPtr:992
Unknown error (0x542)
[!] DuplicateTokenEx fail!

**Comment by BeichenDream** [comment]
当前用户需要有SeImpersonatePrivilege权限

服务都有这个权限,例如IIS,mssql,Apache
